services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart: unless-stopped

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    network_mode: host
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge

  rasp-bridge:
    container_name: rasp-bridge
    build: ./rasp-bridge
    restart: always
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pid: host
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket

  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${HOME}/syncthing:/var/syncthing
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - ./homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    env_file:
      - ./homepage/config/.env
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
