services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart: unless-stopped

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    network_mode: host
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
