- 📰 Медіа та Чтиво:
    - Texty.org.ua:
        - icon: https://texty.org.ua/static/core/images/favicon.ico
          href: https://texty.org.ua/
          description: Журналістика даних
    - YouTube:
        - icon: youtube.png
          abbr: YT
          href: https://youtube.com/
    - Hacker News:
        - icon: https://news.ycombinator.com/y18.svg
          href: https://news.ycombinator.com/
          description: Tech news

- 👨‍💻 IT та Робота:
    - DOU:
        - icon: code.png
          href: https://dou.ua/
          description: Спільнота програмістів
    - GitHub:
        - icon: github-light.png
          href: https://github.com/
          description: My Repos
    - Gemini:
        - icon: google.png
          href: https://gemini.google.com/


- 🛠 Інструменти:
    - Speedtest:
        - icon: cloudflare.png
          href: https://speed.cloudflare.com/
    - Speedtest Local:
        - icon: internet.png
          href: http://192.168.1.61:8085
    - Router:
        - icon: router.png # або ubnt.png, mikrotik.png
          href: http://192.168.1.1
