# https://gethomepage.dev/latest/configs/services/
- Personal:
    - Pi-hole:
        icon: pi-hole.png
        href: http://{{HOMEPAGE_VAR_IP}}:80/admin/
        description: Network-wide Ad Block
        widget:
            version: 6
            type: pihole
            url: http://pihole:80
            key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
    - Homebridge:
        icon: homebridge.png
        href: http://{{HOMEPAGE_VAR_IP}}:8581
        description: Apple HomeKit integration
        widget:
            type: homebridge
            url: http://{{HOMEPAGE_VAR_IP}}:8581
            username: {{HOMEPAGE_VAR_HOMEBRIDGE_USER}}
            password: {{HOMEPAGE_VAR_HOMEBRIDGE_PASS}}
    - Syncthing:
        icon: syncthing.png
        href: http://{{HOMEPAGE_VAR_IP}}:8384
        description: File Synchronization
        ping: {{HOMEPAGE_VAR_IP}}
    - VPN:
        icon: openvpn.png
        description: Router VPN
        widget:
            type: customapi
            url: http://{{HOMEPAGE_VAR_IP}}:8000/vpn/status?format=json
            refresh: 5000 # 5 seconds
            mappings:
              - field: status
                label: Status
                format: text

- News:
    - BBC Ukrainian:
        icon: rss.png
        href: https://www.bbc.com/ukrainian
        description: Latest news from BBC Ukrainian
        widget:
            type: rss
            url: https://feeds.bbci.co.uk/ukrainian/rss.xml
            limit: 3
    - Hacker News:
        icon: ycombinator.png
        href: https://news.ycombinator.com
        description: Tech news
        widget:
            type: rss
            url: https://news.ycombinator.com/rss
            limit: 3
    - Texty.org.ua:
        icon: rss.png
        href: https://texty.org.ua
        description: Data journalism
        widget:
            type: rss
            url: https://texty.org.ua/articles/feed.xml
            limit: 3
