# https://gethomepage.dev/latest/configs/services/
- Personal:
    - Pi-hole:
        icon: pi-hole.png
        href: http://{{HOMEPAGE_VAR_IP}}:80/admin/
        description: Network-wide Ad Block
        widget:
            type: pihole
            url: http://pihole:80
            key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
    - Homebridge:
        icon: homebridge.png
        href: http://{{HOMEPAGE_VAR_IP}}:8581
        description: Apple HomeKit integration
        widget:
            type: homebridge
            url: http://{{HOMEPAGE_VAR_IP}}:8581
            username: {{HOMEPAGE_VAR_HOMEBRIDGE_USER}}
            password: {{HOMEPAGE_VAR_HOMEBRIDGE_PASS}}
    - Syncthing:
        icon: syncthing.png
        href: http://{{HOMEPAGE_VAR_IP}}:8384
        description: File Synchronization
        widget:
            type: syncthing
            url: http://syncthing:8384
            key: {{HOMEPAGE_VAR_SYNCTHING_API_KEY}}
