# https://gethomepage.dev/latest/configs/widgets/
- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: xl
    format:
        dateStyle: short
        timeStyle: short
        hour12: false

- search:
    provider: google
    target: _blank
